'use strict';
// ISO 639-1 codes accepted by Whisper-style transcription APIs.

const LANGUAGES = [
  ['auto', 'Auto-detect'],
  ['en', 'English'],
  ['ur', 'Urdu'],
  ['hi', 'Hindi'],
  ['pa', 'Punjabi'],
  ['ar', 'Arabic'],
  ['bn', 'Bengali'],
  ['fa', 'Persian'],
  ['ps', 'Pashto'],
  ['sd', 'Sindhi'],
  ['es', 'Spanish'],
  ['fr', 'French'],
  ['de', 'German'],
  ['it', 'Italian'],
  ['pt', 'Portuguese'],
  ['nl', 'Dutch'],
  ['ru', 'Russian'],
  ['uk', 'Ukrainian'],
  ['pl', 'Polish'],
  ['tr', 'Turkish'],
  ['zh', 'Chinese'],
  ['ja', 'Japanese'],
  ['ko', 'Korean'],
  ['vi', 'Vietnamese'],
  ['th', 'Thai'],
  ['id', 'Indonesian'],
  ['ms', 'Malay'],
  ['tl', 'Tagalog'],
  ['sw', 'Swahili'],
  ['ta', 'Tamil'],
  ['te', 'Telugu'],
  ['mr', 'Marathi'],
  ['gu', 'Gujarati'],
  ['kn', 'Kannada'],
  ['ml', 'Malayalam'],
  ['ne', 'Nepali'],
  ['si', 'Sinhala'],
  ['he', 'Hebrew'],
  ['el', 'Greek'],
  ['cs', 'Czech'],
  ['sk', 'Slovak'],
  ['hu', 'Hungarian'],
  ['ro', 'Romanian'],
  ['bg', 'Bulgarian'],
  ['hr', 'Croatian'],
  ['sr', 'Serbian'],
  ['sl', 'Slovenian'],
  ['da', 'Danish'],
  ['sv', 'Swedish'],
  ['no', 'Norwegian'],
  ['fi', 'Finnish'],
  ['et', 'Estonian'],
  ['lv', 'Latvian'],
  ['lt', 'Lithuanian'],
  ['ca', 'Catalan'],
  ['az', 'Azerbaijani'],
  ['kk', 'Kazakh'],
  ['uz', 'Uzbek'],
  ['af', 'Afrikaans'],
].map(([code, name]) => ({ code, name }));

function languageName(code) {
  const hit = LANGUAGES.find((l) => l.code === code);
  return hit ? hit.name : '';
}

module.exports = { LANGUAGES, languageName };
